### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by adamhsparks** [sithjaisong/network#13]
Line 7 is unclear, revise.

Line 23 says for "each data set", I thought you only had one data set where you combined SKEP Phase I and Phase II? Please clarify.

Links to your individual R scripts would be good to have here when referencing them.

Line 34 says that the output will be able to compare the differences? I don't think that's possible. Reword for clarity.

Check spelling in the names of all R scripts. There are several spelling errors that I noted in them.

**Comment by adamhsparks** [comment]
There are still spelling and grammar issues with this document that need to be corrected.

Check the headers in particular where correlation is misspelled, etc.

**Comment by sithjaisong** [comment]
corrected grammar and comments at line 7, 23, and 34, added url of each script in README.

**Comment by adamhsparks** [comment]
Still have spelling errors, in particular the first heading, correlation is misspelled.
